## Numpy Practice Session

In [1]:
#import the numpy library
import numpy as np

In [2]:
#1-D array
food=np.array(["Pakora","Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(price)

3

In [7]:
len(food)

3

In [10]:
#price[2]
price[0:]

array([5, 5, 5])

In [11]:
food[1]

'Samosa'

In [12]:
 price.mean()

5.0

In [14]:
#zeroes method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
#ones method
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
#empty method
np.empty(5)

array([1., 1., 1., 1., 1.])

In [17]:
#range to 10
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
#specify interval (2, 20 is for range from 2 to 20 and last 2 is for interval)
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.arange(2,30,5)

array([ 2,  7, 12, 17, 22, 27])

In [21]:
np.linspace(1,10,num=5) #show total 5 number between 1 and 10 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
#specify your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [24]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Array Function

In [27]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [29]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [30]:
b=np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [ ]:
np.concatenate((a,b))